export enum Origin {
  AMERICAN = 'American',
  BRAZILIAN = 'Brazilian',
  CAMEROONIAN = 'Cameroonian',
  CHINESE = 'Chinese',
  EGYPTIAN = 'Egyptian',
  ETHIOPIAN = 'Ethiopian',
  FRENCH = 'French',
  GHANAIAN = 'Ghanaian',
  GERMAN = 'German',
  INDIAN = 'Indian',
  ITALIAN = 'Italian',
  IVORIAN = 'Ivorian',
  JAPANESE = 'Japanese',
  KOREAN = 'Korean',
  MEDITERRANEAN = 'Mediterranean',
  MEXICAN = 'Mexican',
  MOROCCAN = 'Moroccan',
  NIGERIAN = 'Nigerian',
  RUSSIAN = 'Russian',
  SENEGALESE = 'Senegalese',
  SOUTH_AFRICAN = 'South African',
  SPANISH = 'Spanish',
  THAI = 'Thai',
  TUNISIAN = 'Tunisian',
  UNKNOWN = 'Unknown',
  VIETNAMESE = 'Vietnamese',
}

export const ORIGIN_OPTIONS: { value: Origin; label: string }[] = Object.values(Origin).map(v => ({ value: v as Origin, label: v }));